config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  resources :approvals
  resources :items
  resources :requests
  resources :users
  
 

  root 'welcome#index'

end

app/models/approval.rb
class Approval < ActiveRecord::Base
	belongs_to :request, class_name: 'Request', foreign_key: :order_id
	belongs_to :approver, class_name: 'User', foreign_key: :approver_id
end

app/controllers/approvals_controller.rb
class ApprovalsController < ApplicationController
  before_action :set_approval, only: [:show, :edit, :update, :destroy]

  # GET /approvals
  # GET /approvals.json
  def index
    @approvals = Approval.all
  end

  # GET /approvals/1
  # GET /approvals/1.json
  def show
  end

  # GET /approvals/new
  def new
    @approval = Approval.new
  end

  # GET /approvals/1/edit
  def edit
  end

  # POST /approvals
  # POST /approvals.json
  def create
    @approval = Approval.new(approval_params)

    respond_to do |format|
      if @approval.save
        format.html { redirect_to @approval, notice: 'Approval was successfully created.' }
        format.json { render :show, status: :created, location: @approval }
      else
        format.html { render :new }
        format.json { render json: @approval.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /approvals/1
  # PATCH/PUT /approvals/1.json
  def update
    respond_to do |format|
      if @approval.update(approval_params)
        format.html { redirect_to @approval, notice: 'Approval was successfully updated.' }
        format.json { render :show, status: :ok, location: @approval }
      else
        format.html { render :edit }
        format.json { render json: @approval.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /approvals/1
  # DELETE /approvals/1.json
  def destroy
    @approval.destroy
    respond_to do |format|
      format.html { redirect_to approvals_url, notice: 'Approval was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_approval
      @approval = Approval.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def approval_params
      params.require(:approval).permit(:order_id, :approver_id, :approved, :comments, :created_at)
    end
end

app/helpers/approvals_helper.rb
module ApprovalsHelper
end

app/views/approvals/_form.html.erb
<%= form_for(@approval) do |f| %>
  <% if @approval.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@approval.errors.count, "error") %> prohibited this approval from being saved:</h2>

      <ul>
      <% @approval.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :order_id %><br>
    <%= f.number_field :order_id %>
  </div>
  <div class="field">
    <%= f.label :approver_id %><br>
    <%= f.number_field :approver_id %>
  </div>
  <div class="field">
    <%= f.label :approved %><br>
    <%= f.check_box :approved %>
  </div>
  <div class="field">
    <%= f.label :comments %><br>
    <%= f.text_area :comments %>
  </div>
  <div class="field">
    <%= f.label :created_at %><br>
    <%= f.datetime_select :created_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/approvals/edit.html.erb
<h1>Editing Approval</h1>

<%= render 'form' %>

<%= link_to 'Show', @approval %> |
<%= link_to 'Back', approvals_path %>

app/views/approvals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Approvals</h1>

<table>
  <thead>
    <tr>
      <th>Order</th>
      <th>Approver</th>
      <th>Approved</th>
      <th>Comments</th>
      <th>Created at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @approvals.each do |approval| %>
      <tr>
        <td><%= approval.order_id %></td>
        <td><%= approval.approver_id %></td>
        <td><%= approval.approved %></td>
        <td><%= approval.comments %></td>
        <td><%= approval.created_at %></td>
        <td><%= link_to 'Show', approval %></td>
        <td><%= link_to 'Edit', edit_approval_path(approval) %></td>
        <td><%= link_to 'Destroy', approval, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Approval', new_approval_path %>

app/views/approvals/new.html.erb
<h1>New Approval</h1>

<%= render 'form' %>

<%= link_to 'Back', approvals_path %>

app/views/approvals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Order:</strong>
  <%= @approval.order_id %>
</p>

<p>
  <strong>Approver:</strong>
  <%= @approval.approver_id %>
</p>

<p>
  <strong>Approved:</strong>
  <%= @approval.approved %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @approval.comments %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @approval.created_at %>
</p>

<%= link_to 'Edit', edit_approval_path(@approval) %> |
<%= link_to 'Back', approvals_path %>