config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  resources :approvals
  resources :items
  resources :requests
  resources :users
  
 

  root 'welcome#index'

end

app/models/request.rb
class Request < ActiveRecord::Base
	belongs_to :creator, class_name: 'User', foreign_key: :created_by
	belongs_to :first_approved_by, class_name: 'User', foreign_key: :first_approver_id
	has_many :items
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  

  before_action :authenticate_user!, only: [:new, :create]

  before_action :set_request, only: [:show, :destroy]

  # GET /requests
  # GET /requests.json
  def index
    @requests = Request.all
  end

  def user_requests
    current_user.requests
  end

  # GET /requests/1
  # GET /requests/1.json
  def show
  end

  # GET /requests/new
  def new
    @request = Request.new
  end

  # GET /requests/1/edit
  def edit
    @request = Request.find(params[:id])
  end

  # POST /requests
  # POST /requests.json
  def create
    @request = current_user.requests.build(request_params)

    @request.submitted = true

    respond_to do |format|
      if @request.save
        format.html { redirect_to @request, notice: 'Request was successfully created.' }
        format.json { render :show, status: :created, location: @request }
        
      else
        format.html { render :new }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1
  # PATCH/PUT /requests/1.json
  def update
    respond_to do |format|

      @request = Request.find(params[:id])

      @request.submitted = true

      if @request.update(request_params)
        format.html { redirect_to @request, notice: 'Request was successfully updated.' }
        format.json { render :show, status: :ok, location: @request }
      else
        format.html { render :edit }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @request.destroy
    respond_to do |format|
      format.html { redirect_to requests_url, notice: 'Request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_params
      params.require(:request).permit(:required_by, :justification, :first_approver_id, :final_approval)
    end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_form.html.erb
<%= form_for(@request) do |f| %>
  <% if @request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% @request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  


  <%= f.label :created_by %>
  <%= f.label current_user.full_name %>

   

    <div class="field">
      <%= f.label :required_by %><br>
      <%= f.date_select :required_by %>
    </div>
    <div class="field">
      <%= f.label :justification %><br>
      <%= f.text_area :justification %>
    </div>
    <%= f.label :first_approver_id %><br>
    <%= f.collection_select :first_approver_id, User.all, :id, :full_name %>
  <% if @request.persisted? %>
    <div class="field">
      <%= f.label :final_approval %><br>
      <%= f.check_box :final_approval %>
    </div>
   <% end %> 

    <p> </p>
 
    <div class="actions">
      <%= f.submit %>


<% end %>

app/views/requests/edit.html.erb
<h1>Editing Request</h1>

<%= render 'form' %>


<%= link_to 'Back', user_path(current_user) %>

app/views/requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Requests</h1>

<table>
  <thead>
    <tr>
      <th>Created by</th>
      <th>Required by</th>
      <th>Justification</th>
      <th>First approver</th>
      <th>Submitted</th>
      <th>Final approval</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @requests.each do |request| %>
      <tr>
        <td><%= request.created_by %></td>
        <td><%= request.required_by %></td>
        <td><%= request.justification %></td>
        <td><%= request.first_approver_id %></td>
        <td><%= request.submitted %></td>
        <td><%= request.final_approval %></td>
        <td><%= link_to 'Show', request %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Request', new_request_path %>

app/views/requests/new.html.erb
<h1>New Request</h1>

<%= render 'form' %>

<%= link_to 'Nah, I just wanna see my requests', user_path(current_user) %>

app/views/requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Created by:</strong>
  <%= @request.creator.full_name %>
</p>

<p>
  <strong>Required by:</strong>
  <%= @request.required_by %>
</p>

<p>
  <strong>Justification:</strong>
  <%= @request.justification %>
</p>

<p>
  <strong>First approver:</strong>
  <%= @request.first_approved_by.full_name %>
</p>

<p>
  <strong>Submitted:</strong>
  <%= @request.submitted %>
</p>

<p>
  <strong>Final approval:</strong>
  <%= @request.final_approval %>
</p>


<%= link_to 'Back', user_path(current_user) %>